[package]
name = "justcompress"
description = "An universal lossless compression algorithm that prioritizes compression size"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
